version: '3.8'

services:
  dev:
    image: skillsrecommenderapi/dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https.pfx
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true

  release:
    image: skillsrecommenderapi/release
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5443:5443
    environment:
      - ASPNETCORE_URLS=https://+:5443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https.pfx